version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DOCKER_ENVIRONMENT=True
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-default-key-change-me}
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate &&
               gunicorn config.wsgi:application --bind 0.0.0.0:8000"
  
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume: